name: Webhook Logger

on:
  repository_dispatch:
    types: [webhook-log]

jobs:
  log-webhook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log webhook data
        run: |
          echo "=== Webhook Data ==="
          echo "Query Parameters:"
          echo '${{ toJson(github.event.client_payload.query_params) }}' | jq .
          echo ""
          echo "Body:"
          echo '${{ toJson(github.event.client_payload.body) }}' | jq .
